version: '3.7'

networks:
  PonyCoffee:
    driver: bridge

services:
  nginx:
    build: 
      context: .
      dockerfile: docker/Nginx.Dockerfile
    ports:
      - 8080:80
    volumes:
      - ./:/var/www/PonyCoffee
    networks:
      - PonyCoffee 
    container_name: PCNginx
    depends_on:
      - app

  app:
    build:
      context: ./
      dockerfile: docker/Fpm.Dockerfile
    restart: unless-stopped
    working_dir: /var/www/PonyCoffee
    volumes:
      - ./:/var/www/PonyCoffee
    networks:
      - PonyCoffee
    container_name: PCApp
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    ports:
      - 33061:3306
    volumes:
      - ./tmp/db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: password12345
    networks:
      - PonyCoffee
    container_name: PCMysql