version: '3.7'

networks:
  projectNetwork:
    driver: bridge

services:
  nginx:
    build:
      context: .
      dockerfile: docker/Nginx.Dockerfile
    ports:
      - 8080:80
    volumes:
      - ./:/var/www/PonyCoffee
    networks:
      - projectNetwork
    container_name: PC_Nginx
    depends_on:
      - app

  app:
    build:
      context: ./
      dockerfile: docker/Fpm.Dockerfile
    restart: unless-stopped
    working_dir: /var/www/PonyCoffee
    volumes:
      - ./:/var/www/PonyCoffee
    extra_hosts:
        -   "host.docker.internal:host-gateway"
    environment:
        PHP_IDE_CONFIG: serverName=Docker
    networks:
      - projectNetwork
    container_name: PC_App
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    ports:
      - 33061:3306
    volumes:
      - ./tmp/db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: password12345
    networks:
      - projectNetwork
    container_name: PC_Mysql

  redis:
      image: redis:latest
      ports:
          - 6379:6479
      volumes:
          -   ./tmp/redis:/var/lib/redis
      networks:
          - projectNetwork
      container_name: PC_Redis
